# Generated by Django 4.1.2 on 2022-10-17 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_user_is_client_user_is_worker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_worker',
        ),
    ]
