# Generated by Django 4.1.2 on 2022-10-20 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_user_is_worker'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.customercategory'),
        ),
    ]
