# Generated by Django 4.1.2 on 2022-10-17 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderpaper',
            name='type',
            field=models.CharField(choices=[('Pedido', 'Pedido'), ('Entrega', 'Entrega'), ('EntregaAceptada', 'Entrega Aceptada'), ('EntregaRechazada', 'Entrega Rechazada')], default='Pedido', max_length=20),
        ),
    ]
